openapi: 3.0.0
info:
  description: ActivityResponse model
  title: ActivityResponse model
  version: 1.0.0
paths:

components:
  schemas:
    ActivityResponse:
      allOf:
        - $ref: '../BaseDto.yml#/components/schemas/BaseDto'
      properties:
        number:
          type: string
        name:
          type: string
        startDate:
          type: string
          format: date-time
        duration:
          type: integer
        trainer:
          $ref: '../account/AccountGeneralResponse.yml#/components/schemas/AccountGeneralResponse'
        active:
          type: boolean
        capacity:
          type: integer