openapi: 3.0.0
info:
  description: ActivityRequestPost model
  title: ActivityRequestPost model
  version: 1.0.0
paths:

components:
  schemas:
    ActivityRequestPost:
      required:
        - activityNumber
        - title
        - startDate
        - duration
        - trainer
        - capacity
      properties:
        activityNumber:
          type: string
          pattern: "^ACT[0-9]{3}$"
        title:
          type: string
        startDate:
          type: string
          format: date-time
        duration:
          type: integer
          minimum: 1
        trainer:
          type: string
        capacity:
          type: integer