openapi: 3.0.0
info:
  description: TrainingPlanResponse model
  title: TrainingPlanResponse model
  version: 1.0.0
paths:

components:
  schemas:
    TrainingPlanResponse:
      properties:
        number:
          type: string
        title:
          type: string
        trainingType:
          type: string
        personalTrainingsNumber:
          type: integer
        trainer:
          type: string
        price:
          type: number