openapi: 3.0.0
info:
  description: TrainingPlanRequestPost model
  title: TrainingPlanRequestPost model
  version: 1.0.0
paths:

components:
  schemas:
    TrainingPlanRequestPost:
      type: object
      required:
        - trainingPlanNumber
        - title
        - trainingType
        - personalTrainingsNumber
        - trainer
        - price
      properties:
        trainingPlanNumber:
          type: string
          pattern: "^TRA[0-9]{3}$"
        title:
          type: string
        trainingType:
          type: string
          enum:
            - CARDIO
            - STRENGTH
            - CALISTHENICS
            - CIRCUIT
            - INTERVALS
            - CROSSFIT
            - FUNCTIONAL
        personalTrainingsNumber:
          type: integer
          minimum: 0
        trainer:
          type: string
        price:
          type: number
          minimum: 1