openapi: 3.0.0
info:
  description: AccountRequestPut model
  title: AccountRequestPut model
  version: 1.0.0
paths:

components:
  schemas:
    AccountRequestPut:
      properties:
        password:
          type: string
          pattern: "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$ %^&*-]).{8,}$"