openapi: 3.0.0
info:
  description: AccountGeneralResponse model
  title: AccountGeneralResponse model
  version: 1.0.0
paths:

components:
  schemas:
    AccountGeneralResponse:
      properties:
        login:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        active:
          type: boolean
        confirmed:
          type: boolean