openapi: 3.0.0
info:
  description: AccountRequestPut model
  title: AccountRequestPut model
  version: 1.0.0
paths:

components:
  schemas:
    AccountRequestPut:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        language:
          type: string
          maxLength: 5
        gymMember:
          type: boolean
        phoneNumber:
          type: string
          pattern: "^[0-9]{9,12}$"
        active:
          type: boolean