openapi: 3.0.0
info:
  description: CredentialsRequest model
  title: CredentialsRequest model
  version: 1.0.0
paths:

components:
  schemas:
    CredentialsRequest:
      properties:
        login:
          type: string
        password:
          type: string