openapi: 3.0.0
info:
  description: TrainingTypeResponse model
  title: TrainingTypeResponse model
  version: 1.0.0
paths:

components:
  schemas:
    TrainingTypeResponse:
      properties:
        title:
          type: string