openapi: 3.0.0
info:
  description: DietRequestPost model
  title: DietRequestPost model
  version: 1.0.0
paths:

components:
  schemas:
    DietRequestPost:
      required:
        - dietNumber
        - title
        - dietType
        - calories
        - meals_number
        - price
      properties:
        dietNumber:
          type: string
          pattern: "^DIE[0-9]{3}$"
        title:
          type: string
        dietType:
          type: string
          enum:
            - LOW-CALORIE
            - HIGH-PROTEIN
            - LOW-CARBOHYDRATE
            - HIGH-CARBOHYDRATE
            - VEGE
        calories:
          type: integer
          minimum: 1
        mealsNumber:
          type: integer
          minimum: 1
        price:
          type: number
          minimum: 1