openapi: 3.0.0
info:
  description: DietResponse model
  title: DietResponse model
  version: 1.0.0
paths:

components:
  schemas:
    DietResponse:
      properties:
        number:
          type: string
        title:
          type: string
        dietType:
          type: string
        calories:
          type: integer
        mealsNumber:
          type: integer
        price:
          type: number