openapi: 3.0.0
info:
  description: TrainingPlanRequestPut model
  title: TrainingPlanRequestPut model
  version: 1.0.0
paths:

components:
  schemas:
    TrainingPlanRequestPut:
      type: object
      properties:
        name:
          type: string
        personalTrainingsNumber:
          type: integer
          minimum: 0
        trainer:
          type: string
        price:
          type: number
          minimum: 1
        trainingType:
          type: string
          enum:
            - CARDIO
            - STRENGTH
            - CALISTHENICS
            - CIRCUIT
            - INTERVALS
            - CROSSFIT
            - FUNCTIONAL