openapi: 3.0.0
info:
  description: TrainingPlanResponseList model
  title: TrainingPlanResponseList model
  version: 1.0.0
paths:

components:
  schemas:
    TrainingPlanResponseList:
      type: array
      items:
        $ref: '../training/TrainingPlanResponse.yml#/components/schemas/TrainingPlanResponse'