openapi: 3.0.0
info:
  description: BookingRequestPost model
  title: BookingRequestPost model
  version: 1.0.0
paths:

components:
  schemas:
    BookingRequestPost:
      required:
        - activity
      properties:
        activity:
          type: string
          pattern: "^ACT[0-9]{3}$"
        account:
          type: string