openapi: 3.0.0
info:
  description: BookingResponse model
  title: BookingResponse model
  version: 1.0.0
paths:

components:
  schemas:
    BookingResponse:
      properties:
        number:
          type: string
        account:
          type: string
        activity:
          type: string
        active:
          type: boolean
        completed:
          type: boolean
        pending:
          type: boolean