openapi: 3.0.0
info:
  description: BookingRequestPut model
  title: BookingRequestPut model
  version: 1.0.0
paths:

components:
  schemas:
    BookingRequestPut:
      properties:
        active:
          type: boolean
        completed:
          type: boolean