openapi: 3.0.0
info:
  description: DietTypeResponse model
  title: DietTypeResponse model
  version: 1.0.0
paths:

components:
  schemas:
    DietTypeResponse:
      properties:
        title:
          type: string