openapi: 3.0.0
info:
  description: AccessLevelRequestPost model
  title: AccessLevelRequestPost model
  version: 1.0.0
paths:

components:
  schemas:
    AccessLevelRequestPost:
      required:
        - level
        - account
      properties:
        level:
          type: string
          enum:
            - CLIENT
            - ADMIN
            - TRAINER
        account:
          type: string