openapi: 3.0.0
info:
  description: Swagger API for rest service
  version: 1.0.0
  title: Swagger rest

tags:
  - name: accessLevel
    description: Endpoints related to access levels
  - name: account
    description: Endpoints related to accounts
  - name: activity
    description: Endpoints related to access activities
  - name: booking
    description: Endpoints related to bookings
  - name: diet
    description: Endpoints related to diets
  - name: dietType
    description: Endpoints related to types of diets
  - name: disposableUrl
    description: Endpoints related to disposable urls
  - name: trainingPlan
    description: Endpoints related to trainingPlans
  - name: trainingType
    description: Endpoints related to trainingTypes
  - name: auth
    description: Endpoints related to authorisation and authentication process

paths:
  /accessLevels:
    $ref: './paths/accessLevel/AccessLevel.yml'

  /accounts:
    $ref: './paths/account/Account.yml'

  /accounts/{login}:
    $ref: './paths/account/AccountByLogin.yml'

  /authenticate:
    $ref: './paths/account/Authenticate.yml'

  /trainingPlans:
    $ref: './paths/training/TrainingPlan.yml'

  /trainingPlans/{number}:
    $ref: './paths/training/TrainingPlanByNumber.yml'
          content:
            application/json:
              schema:
                type: string
                description: User's token

components:
  schemas:
    BaseDto:
      $ref: './schemas/BaseDto.yml#/components/schemas/BaseDto'

    AccountGeneralResponse:
      $ref: './schemas/account/AccountGeneralResponse.yml#/components/schemas/AccountGeneralResponse'

    AccessLevelResponse:
      $ref: './schemas/accessLevel/AccessLevelResponse.yml#/components/schemas/AccessLevelResponse'

    AccessLevelResponseList:
      $ref: './schemas/accessLevel/AccessLevelResponseList.yml#/components/schemas/AccessLevelResponseList'

    AccountDetailsResponse:
      $ref: './schemas/account/AccountDetailsResponse.yml#/components/schemas/AccountDetailsResponse'

    AccountGeneralResponseList:
      $ref: './schemas/account/AccountGeneralResponseList.yml#/AccountGeneralResponseList'

    AccountRequest:
      $ref: './schemas/account/AccountRequest.yml#/components/schemas/AccountRequest'

    CredentialsRequest:
      $ref: './schemas/account/CredentialsRequest.yml#/components/schemas/CredentialsRequest'

    DietResponse:
      $ref:  './schemas/diet/DietResponse.yml#/components/schemas/DietResponse'

    DietResponseList:
      $ref: './schemas/diet/DietResponseList.yml#/components/schemas/DietResponseList'

    DietType:
      $ref:  './schemas/diet/DietType.yml#/components/schemas/DietType'

    TrainingPlanRequest:
      $ref: './schemas/training/TrainingPlanRequest.yml#/components/schemas/TrainingPlanRequest'

    TrainingPlanResponse:
      $ref:  './schemas/training/TrainingPlanResponse.yml#/components/schemas/TrainingPlanResponse'

    TrainingPlanResponseList:
      $ref: './schemas/training/TrainingPlanResponseList.yml#/components/schemas/TrainingPlanResponseList'

    TrainingType:
      $ref:  './schemas/training/TrainingType.yml#/components/schemas/TrainingType'

    ERRORUNKNOWN:
      nullable: true
      properties:
        dup:
          type: string