openapi: 3.0.0
info:
  description: Swagger API for rest service
  version: 1.0.0
  title: Swagger rest

tags:
  - name: accessLevel
    description: Endpoints related to access levels
  - name: account
    description: Endpoints related to accounts
  - name: activity
    description: Endpoints related to access activities
  - name: booking
    description: Endpoints related to bookings
  - name: diet
    description: Endpoints related to diets
  - name: dietType
    description: Endpoints related to types of diets
  - name: disposableUrl
    description: Endpoints related to disposable urls
  - name: trainingPlan
    description: Endpoints related to trainingPlans
  - name: trainingType
    description: Endpoints related to trainingTypes
  - name: auth
    description: Endpoints related to authorisation and authentication process

paths:
  /accessLevels:
    $ref: './paths/accessLevel/AccessLevel.yml'

  /accessLevels/{login}/{level}:
    $ref: './paths/accessLevel/AccessLevelByNumber.yml#/LoginAndLevel'

  /accessLevels/{login}:
    $ref: './paths/accessLevel/AccessLevelByNumber.yml#/Login'

  /accounts:
    $ref: './paths/account/Account.yml#/general'

  /accounts/own:
    $ref: './paths/account/Account.yml#/own'

  /accounts/own/trainingPlans:
    $ref: './paths/account/Account.yml#/trainingPlan/withoutParam'

  /accounts/own/trainingPlans/{number}:
    $ref: './paths/account/Account.yml#/trainingPlan/remove'

  /accounts/own/diets:
    $ref: './paths/account/Account.yml#/diet/withoutParam'

  /accounts/own/diets/{number}:
    $ref: './paths/account/Account.yml#/diet/remove'

  /accounts/{login}:
    $ref: './paths/account/AccountByLogin.yml'

  /accounts/{login}/trainingPlans:
    $ref: './paths/account/AccountByLogin.yml#/trainingPlan/withoutParam'

  /accounts/{login}/diets:
    $ref: './paths/account/AccountByLogin.yml#/diet/withoutParam'

  /authenticate:
    $ref: './paths/account/Authenticate.yml#/authenticate'

  /confirmRegistration/{token}:
    $ref: './paths/account/Authenticate.yml#/confirm'

  /trainingPlans:
    $ref: './paths/training/TrainingPlan.yml'

  /trainingPlans/{number}:
    $ref: './paths/training/TrainingPlanByNumber.yml'

  /trainingPlans/trainer/{login}:
    $ref: './paths/training/TrainingPlanByTrainerLogin.yml'

  /diets:
    $ref: './paths/diet/Diet.yml'

  /diets/{number}:
    $ref: './paths/diet/DietByNumber.yml'

  /activities:
    $ref: './paths/activity/Activity.yml'

  /activities/{number}:
    $ref: './paths/activity/ActivityByNumber.yml#/activityNumber'

  /activities/trainer/{login}:
    $ref: './paths/activity/ActivityByNumber.yml#/trainerLogin'

  /bookings:
    $ref: './paths/booking/Booking.yml#/all'

  /bookings/own:
    $ref: './paths/booking/Booking.yml#/own'

  /bookings/own/{number}:
    $ref: './paths/booking/BookingByNumber.yml#/own/get'

  /bookings/own/{number}/cancel:
    $ref: './paths/booking/BookingByNumber.yml#/own/cancel'

  /bookings/{number}:
    $ref: './paths/booking/BookingByNumber.yml#/all/get'

  /bookings/{number}/cancel:
    $ref: './paths/booking/BookingByNumber.yml#/all/cancel'

  /bookings/{number}/complete:
    $ref: './paths/booking/BookingByNumber.yml#/all/complete'

  /dietTypes:
    $ref: './paths/dietType/DietType.yml'

  /trainingTypes:
    $ref: './paths/trainingType/TrainingType.yml'

components:
  schemas:

    BaseDto:
      $ref: './schemas/BaseDto.yml#/components/schemas/BaseDto'

    AccountGeneralResponse:
      $ref: './schemas/account/AccountGeneralResponse.yml#/components/schemas/AccountGeneralResponse'

    AccessLevelResponse:
      $ref: './schemas/accessLevel/AccessLevelResponse.yml#/components/schemas/AccessLevelResponse'

    AccessLevelRequestPut:
      $ref: './schemas/accessLevel/AccessLevelRequestPut.yml#/components/schemas/AccessLevelRequestPut'

    AccessLevelRequestPost:
      $ref: './schemas/accessLevel/AccessLevelRequestPost.yml#/components/schemas/AccessLevelRequestPost'

    AccessLevelResponseList:
      $ref: './schemas/accessLevel/AccessLevelResponseList.yml#/components/schemas/AccessLevelResponseList'

    AccountDetailsResponse:
      $ref: './schemas/account/AccountDetailsResponse.yml#/components/schemas/AccountDetailsResponse'

    AccountGeneralResponseList:
      $ref: './schemas/account/AccountGeneralResponseList.yml#/AccountGeneralResponseList'

    AccountRequestPut:
      $ref: './schemas/account/AccountRequestPut.yml#/components/schemas/AccountRequestPut'

    AccountRequestPost:
      $ref: './schemas/account/AccountRequestPost.yml#/components/schemas/AccountRequestPost'

    CredentialsRequest:
      $ref: './schemas/account/CredentialsRequest.yml#/components/schemas/CredentialsRequest'

    DietResponse:
      $ref:  './schemas/diet/DietResponse.yml#/components/schemas/DietResponse'

    DietResponseList:
      $ref: './schemas/diet/DietResponseList.yml#/components/schemas/DietResponseList'

    DietRequestPut:
      $ref: './schemas/diet/DietRequestPut.yml#/components/schemas/DietRequestPut'

    DietRequestPost:
      $ref: './schemas/diet/DietRequestPost.yml#/components/schemas/DietRequestPost'

    DietTypeResponse:
      $ref:  './schemas/dietType/DietTypeResponse.yml#/components/schemas/DietTypeResponse'

    ActivityRequestPost:
      $ref: './schemas/activity/ActivityRequestPost.yml#/components/schemas/ActivityRequestPost'

    ActivityRequestPut:
      $ref: './schemas/activity/ActivityRequestPut.yml#/components/schemas/ActivityRequestPut'

    ActivityResponse:
      $ref: './schemas/activity/ActivityResponse.yml#/components/schemas/ActivityResponse'

    ActivityResponseList:
      $ref: './schemas/activity/ActivityResponseList.yml#/components/schemas/ActivityResponseList'

    BookingRequestPost:
      $ref: './schemas/booking/BookingRequestPost.yml#/components/schemas/BookingRequestPost'

    BookingResponse:
      $ref: './schemas/booking/BookingResponse.yml#/components/schemas/BookingResponse'

    BookingResponseList:
      $ref: './schemas/booking/BookingResponseList.yml#/components/schemas/BookingResponseList'

    TrainingPlanRequestPost:
      $ref: './schemas/training/TrainingPlanRequestPost.yml#/components/schemas/TrainingPlanRequestPost'

    TrainingPlanRequestPut:
      $ref: './schemas/training/TrainingPlanRequestPut.yml#/components/schemas/TrainingPlanRequestPut'

    TrainingPlanResponse:
      $ref: './schemas/training/TrainingPlanResponse.yml#/components/schemas/TrainingPlanResponse'

    TrainingPlanResponseList:
      $ref: './schemas/training/TrainingPlanResponseList.yml#/components/schemas/TrainingPlanResponseList'

    TrainingTypeResponse:
      $ref:  './schemas/trainingType/TrainingTypeResponse.yml#/components/schemas/TrainingTypeResponse'