openapi: 3.0.0
info:
  description: DietRequestPut model
  title: DietRequestPut model
  version: 1.0.0
paths:

components:
  schemas:
    DietRequestPut:
      properties:
        name:
          type: string
        dietType:
          type: string
          enum:
            - LOW-CALORIE
            - HIGH-PROTEIN
            - LOW-CARBOHYDRATE
            - HIGH-CARBOHYDRATE
            - VEGE
        calories:
          type: integer
          minimum: 1
        mealsNumber:
          type: string
          minimum: 1
        price:
          type: number
          minimum: 1