openapi: 3.0.0
info:
  description: DietType model
  title: DietType model
  version: 1.0.0
paths:

components:
  schemas:
    DietType:
      allOf:
        - $ref: '../BaseDto.yml#/components/schemas/BaseDto'
      properties:
        name:
          type: string