get:
  tags:
    - trainingPlan
  summary: Get training plan
  description: Find training plan with given number
  operationId: getTrainingPlan
  parameters:
    - in: path
      name: number
      schema:
        type: string
      required: true
  responses:
    200:
      description: Operation successful
      content:
        application/json:
          schema:
            $ref: '../../schemas/training/TrainingPlanDetailsResponse.yml#/components/schemas/TrainingPlanDetailsResponse'

put:
  tags:
    - trainingPlan
  summary: Update training plan
  description: Update existing training plan with given number
  operationId: updateTrainingPlan
  parameters:
    - in: path
      name: number
      schema:
        type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/training/TrainingPlanRequestPut.yml#/components/schemas/TrainingPlanRequestPut'
  responses:
    200:
      description: Operation successful
      content:
        application/json:
          schema:
            $ref: '../../schemas/training/TrainingPlanDetailsResponse.yml#/components/schemas/TrainingPlanDetailsResponse'

delete:
  tags:
    - trainingPlan
  summary: Remove training plan
  description: Remove training plan with the given number
  operationId: deleteTrainingPlan
  parameters:
    - in: path
      name: number
      schema:
        type: string
      required: true
  responses:
    200:
      description: Operation successful